.PHONY: clean All

All:
	@echo "----------Building project:[ LinearDSFirst - Debug ]----------"
	@cd "LinearDSFirst" && "$(MAKE)" -f  "LinearDSFirst.mk"
clean:
	@echo "----------Cleaning project:[ LinearDSFirst - Debug ]----------"
	@cd "LinearDSFirst" && "$(MAKE)" -f  "LinearDSFirst.mk" clean
